# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=100, verbose_name='ชื่อจังหวัด (ไทย)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Province Name (EN)')),
                ('latitude', models.FloatField(verbose_name='ละติจูด')),
                ('longitude', models.FloatField(verbose_name='ลองจิจูด')),
                ('region', models.CharField(default='', max_length=50, verbose_name='ภูมิภาค')),
            ],
            options={
                'verbose_name': 'จังหวัด',
                'verbose_name_plural': 'จังหวัด',
                'ordering': ['name_th'],
            },
        ),
        migrations.CreateModel(
            name='DamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid_code', models.CharField(max_length=20, verbose_name='รหัสเขื่อน (RID)')),
                ('dam_name', models.CharField(max_length=200, verbose_name='ชื่อเขื่อน')),
                ('capacity_mcm', models.FloatField(blank=True, null=True, verbose_name='ความจุ (ล้าน ม³)')),
                ('volume_mcm', models.FloatField(blank=True, null=True, verbose_name='ปริมาณน้ำ (ล้าน ม³)')),
                ('storage_percent', models.FloatField(blank=True, null=True, verbose_name='% การเก็บกักน้ำ')),
                ('inflow_cms', models.FloatField(blank=True, null=True, verbose_name='น้ำไหลเข้า (ม³/วินาที)')),
                ('outflow_cms', models.FloatField(blank=True, null=True, verbose_name='น้ำระบาย (ม³/วินาที)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dams', to='flood_alert.province', verbose_name='จังหวัด')),
            ],
            options={
                'verbose_name': 'ข้อมูลอ่างเก็บน้ำ',
                'verbose_name_plural': 'ข้อมูลอ่างเก็บน้ำ',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
                ('forecast_time', models.DateTimeField(verbose_name='เวลาพยากรณ์')),
                ('precipitation_mm', models.FloatField(default=0.0, verbose_name='ปริมาณฝน (มม./ชม.)')),
                ('temperature_c', models.FloatField(blank=True, null=True, verbose_name='อุณหภูมิ (°C)')),
                ('humidity_pct', models.FloatField(blank=True, null=True, verbose_name='ความชื้นสัมพัทธ์ (%)')),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True, verbose_name='ความเร็วลม (กม./ชม.)')),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True, verbose_name='เมฆปกคลุม (%)')),
                ('source', models.CharField(choices=[('open_meteo', 'Open-Meteo'), ('tmd', 'กรมอุตุนิยมวิทยา'), ('manual', 'ป้อนเอง')], default='open_meteo', max_length=20)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='flood_alert.province')),
            ],
            options={
                'verbose_name': 'ข้อมูลสภาพอากาศ',
                'verbose_name_plural': 'ข้อมูลสภาพอากาศ',
                'ordering': ['-forecast_time'],
            },
        ),
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาทำนาย')),
                ('valid_for_time', models.DateTimeField(verbose_name='เวลาที่ใช้ได้ถึง')),
                ('risk_level', models.CharField(choices=[('SAFE', '🟢 ปลอดภัย'), ('LOW', '🟡 เฝ้าระวัง'), ('MODERATE', '🟠 เสี่ยงปานกลาง'), ('HIGH', '🔴 เสี่ยงสูง'), ('CRITICAL', '🚨 วิกฤต')], max_length=10, verbose_name='ระดับความเสี่ยง')),
                ('flood_probability', models.FloatField(default=0.0, verbose_name='ความน่าจะเป็น (%)')),
                ('expected_rain_mm', models.FloatField(default=0.0, verbose_name='ฝนที่คาดการณ์ (มม.)')),
                ('dam_fill_pct', models.FloatField(blank=True, null=True, verbose_name='% น้ำในอ่าง')),
                ('notes', models.TextField(blank=True, default='', verbose_name='หมายเหตุ')),
                ('score_rain', models.FloatField(default=0.0, verbose_name='คะแนนฝน (0-100)')),
                ('score_dam', models.FloatField(default=0.0, verbose_name='คะแนนอ่าง (0-100)')),
                ('score_history', models.FloatField(default=0.0, verbose_name='คะแนนประวัติ (0-100)')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='flood_alert.province')),
            ],
            options={
                'verbose_name': 'ผลการทำนายน้ำท่วม',
                'verbose_name_plural': 'ผลการทำนายน้ำท่วม',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HEAVY_RAIN', '🌧️ ฝนตกหนัก'), ('FLOOD_RISK', '⚠️ เสี่ยงน้ำท่วม'), ('FLOOD_CRITICAL', '🚨 น้ำท่วมวิกฤต'), ('DAM_FULL', '🏞️ อ่างเก็บน้ำเต็ม'), ('DAM_WARNING', '⚠️ อ่างเก็บน้ำเกือบเต็ม')], max_length=20)),
                ('title', models.CharField(max_length=300, verbose_name='หัวข้อการแจ้งเตือน')),
                ('message', models.TextField(verbose_name='ข้อความแจ้งเตือน')),
                ('is_active', models.BooleanField(default=True, verbose_name='ยังใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลารับทราบ')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='flood_alert.province')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flood_alert.floodprediction')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('open_meteo', 'Open-Meteo'), ('rid_dam', 'RID อ่างเก็บน้ำ'), ('gistda', 'GISTDA'), ('tmd', 'กรมอุตุ')], max_length=20)),
                ('status', models.CharField(choices=[('success', '✅ สำเร็จ'), ('error', '❌ ผิดพลาด'), ('partial', '⚠️ บางส่วน')], max_length=10)),
                ('records_fetched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0, verbose_name='ระยะเวลา (มิลลิวินาที)')),
            ],
            options={
                'verbose_name': 'ประวัติการดึงข้อมูล',
                'verbose_name_plural': 'ประวัติการดึงข้อมูล',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['province', 'forecast_time'], name='flood_alert_provinc_c00f30_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['forecast_time'], name='flood_alert_forecas_fb2d62_idx'),
        ),
        migrations.AddIndex(
            model_name='damdata',
            index=models.Index(fields=['rid_code', 'timestamp'], name='flood_alert_rid_cod_fa2e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['province', 'predicted_at'], name='flood_alert_provinc_3b4a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['risk_level'], name='flood_alert_risk_le_9d1e2a_idx'),
        ),
    ]
