# Generated by Django 4.2.16 on 2026-09-27 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flood_alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedRain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_24h_mm', models.FloatField(default=0.0, verbose_name='ฝนสะสม 24 ชม. (มม.)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
            ],
            options={
                'verbose_name': 'ข้อมูลฝนสะสมจริง',
                'verbose_name_plural': 'ข้อมูลฝนสะสมจริง',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='damdata',
            new_name='flood_alert_rid_cod_a6cfb3_idx',
            old_name='flood_alert_rid_cod_fa2e1c_idx',
        ),
        migrations.RenameIndex(
            model_name='floodprediction',
            new_name='flood_alert_provinc_0bff97_idx',
            old_name='flood_alert_provinc_3b4a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='floodprediction',
            new_name='flood_alert_risk_le_741471_idx',
            old_name='flood_alert_risk_le_9d1e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherdata',
            new_name='flood_alert_provinc_912010_idx',
            old_name='flood_alert_provinc_c00f30_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherdata',
            new_name='flood_alert_forecas_0a39a7_idx',
            old_name='flood_alert_forecas_fb2d62_idx',
        ),
        migrations.AlterField(
            model_name='datafetchlog',
            name='source',
            field=models.CharField(choices=[('open_meteo', 'Open-Meteo'), ('rid_dam', 'RID อ่างเก็บน้ำ'), ('gistda', 'GISTDA'), ('tmd', 'กรมอุตุ'), ('thaiwater', 'ThaiWater')], max_length=20),
        ),
        migrations.AddField(
            model_name='observedrain',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_rain', to='flood_alert.province'),
        ),
        migrations.AddIndex(
            model_name='observedrain',
            index=models.Index(fields=['province', 'timestamp'], name='flood_alert_provinc_e3cdad_idx'),
        ),
    ]
